export default [{
    id: 1,
    source: 'images/nature4.jpg',
    category: "nature"
  }, {
    id: 2,
    source: 'images/beach3.jpg',
    category: "beach"
  }, {
    id: 3,
    source: 'images/nature2.jpg',
    category: "nature"
  }, {
    id: 4,
    source: 'images/flower5.jpg',
    category: "flower"
  }, {
    id: 5,
    source: 'images/car2.jpg',
    category: "car"
  }, {
    id: 6,
    source: "images/food.jpg",
    category: "food"
  }, {
    id: 7,
    source: "images/nature.jpg",
    category: "nature"
  }, {
    id: 8,
    source: "images/space4.jpg",
    category: "space"
  }, {
    id: 9,
    source: 'images/space2.jpg',
    category: "space"
  }, {
    id: 10,
    source: "images/flower.jpg",
    category: "flower"
  }, {
    id: 11,
    source: 'images/car1.jpg',
    category: "car"
  }, {
    id: 12,
    source: "images/nature3.jpg",
    category: "nature"
  }, {
    id: 13,
    source: "images/flower3.jpg",
    category: "flower"
  }, {
    id: 14,
    source: "images/car3.jpg",
    category: "car"
  }, {
    id: 15,
    source: "images/food2.jpg",
    category: "food"
  }, {
    id: 16,
    source: "images/beach1.jpg",
    category: "beach"
  }, {
    id: 17,
    source: "images/space.jpg",
    category: "space"
  }, {
    id: 18,
    source: "images/flower4.jpg",
    category: "flower"
  }, {
    id: 19,
    source: "images/food4.jpg",
    category: "food"
  }, {
    id: 20,
    source: "images/car4.jpg",
    category: 'car'
  }, {
    id: 21,
    source: "images/nature5.jpg",
    category: "nature"
  }, {
    id: 22,
    source: "images/beach2.jpg",
    category: "beach"
  }, {
    id: 23,
    source: "images/beach4.jpg",
    category: "beach"
  }, {
    id: 24,
    source: "images/flower2.jpg",
    category: "flower"
  }, {
    id: 25,
    source: "images/beach5.jpg",
    category: "beach"
  }, {
    id: 26,
    source: "images/car5.jpg",
    category: "car"
  }, {
    id: 27,
    source: 'images/food3.jpg',
    category: "food"
  }, {
    id: 28,
    source: "images/beach6.jpg",
    category: "beach"
  }, {
    id: 29,
    source: "images/space5.jpg",
    category: "space"
  }, {
    id: 30,
    source: "images/beach7.jpg",
    category: "beach"
  }]

  